### ISSUE TITLE
Lab 2 review

### ISSUE THREAD

**Issue by Winnie-the-Pooh2019** [LevKolechkov/Java_Lab_2#4]
* [x] В Java числовые переменные автоматически зануляются
* [x] Количество всех элементов в таблице можно посчитать путем перемножения количества строк и столбцов
    ```java
    public double average() {
        // count smth
  
        return (double) sum / rows / cols;
    } 
    ```
* [x] В интерфейсе ```Figure``` не нужно объявлять метод ```toString```, так как он определяется в классе ```Object```.
* [x] Почему ```area()``` имеет тип возвращаемого значения ```Double```?
* [x] Поля классов лучше делать приватными, чтобы избежать внешнего воздействия на них.
* [x] Зачем выбрасывать исключение и тут же его отлавливать? Когда ты в конструкторе указываешь некорректные аргументы, выбрасывается исключение и тут же отлавливается, в ```catch``` выводится сообщение. Однако объект создался со значениями по-умолчанию, которые тоже некорректные :smile:. Поведение программы никак не меняется в зависимости от корректности значений: объект будет создан, только еще и неправильный
    ```java
    class Rectangle {
        public Rectangle(double width, double height){
            setWidth(width);
            setHeight(height);
        }
  
        public void setWidth(Double width) {
            try {
                if (width <= 0) throw new WidthException("Width must be higher than zero");
                else this.width = width;
            } catch (WidthException e) {
                System.out.println(e.getMessage());
            }
        }

        public void setHeight(Double height) {
            // the same as in setWidth
        }   
    }
  
    // some code
    public static void main(String[] args){
        // Выведется сообщение об ошибке, но объект будет создан
        Rectangle rec = new Rectangle(-3, -1);
        
        // Находим площадь для некорректного прямоугольника со сторонами 0, 0
        double area = rec.area();
    }
    ```
    Вместо этого надо было просто выбрасывать исключение при некорректных входных данных и перехватывать его в том месте, где вызывается конструктор или сеттеры:
    ```java
    class Rectangle {
        public Rectangle(double width, double height){
            setWidth(width);
            setHeight(height);
        }
  
        public void setWidth(double width) {
            if (width <= 0) 
                throw new WidthException("Width must be higher than zero");
  
            else this.width = width;
        }

        public void setHeight(Double height) {
            // the same as in setWidth
        }   
    }
  
    // some code
    public static void main(String[] args){
        // Объект не будет проинициальзирован с некорректными аргументами конструктора
        Rectangle rec;
        try {
            rec = new Rectangle(-3, -1);
        } catch (WidthException | HeightException e) {
            System.out.println(e.getMessage());
        }
        
        // Находим площадь только если он существует
        if (rec != null)
            double area = rec.area();
    }
    ```
* [x] Цилиндр обобщенный, то есть основанием у него может выступать любая фигура, а не только круг

**Comment by LevKolechkov** [comment]
* [ ] В классе ```Cylinder``` отсутствует проверка на null основание цилиндра, что чревато ```NullPointerException```
